### ISSUE TITLE
error: openlogin-sdk.init or openlogin-sdk.redirectUrl is not set

### ISSUE THREAD

**Issue by AndreyMaksimkin** [Web3Auth/web3auth-swift-sdk#34]
This bug is reproduces only for the first attempt of autorisation with Google provider. I use v3.5.1. What's wrong and how to fix that?
![IMG_0299](https://user-images.githubusercontent.com/6286808/202168798-d730f398-9757-408d-8e6d-0685d1f149ed.png)

**Comment by Kshatriyan04** [comment]
@chaitanyapotti I get this same issue in ios devices only at first time of login. Even after uninstalling and reinstalling I am unable to reproduce this. Please check this issue.

**Comment by samuelezedi** [comment]
@chaitanyapotti I am currently experiencing this issue, any particular fix pls?

**Comment by chaitanyapotti** [comment]
Fixed in 6.0.0. Pls upgrade
