### ISSUE TITLE
'SWIFT TASK CONTINUATION MISUSE' when login func is called 

### ISSUE THREAD

**Issue by LinhNH2096** [Web3Auth/web3auth-swift-sdk#41]
Hi, I've met an issue 'SWIFT TASK CONTINUATION MISUSE: login(_:) tried to resume its continuation more than once, throwing unknownError!' when I call login() function. But it does not happen often. 
Throw error at line 149 in Web3Auth class.

```
    if !(authSession?.start() ?? false) {
                continuation.resume(throwing: Web3AuthError.unknownError)
            }
```
How can i resolve at my app site? or it's your?

**Comment by grvgoel81** [comment]
Pls use latest version.
